### ISSUE TITLE
Cannot run javascript-obfuscator from CLI for node version 10.15.3

### ISSUE THREAD

**Issue by verina09** [javascript-obfuscator/javascript-obfuscator#876]
Hi, does the latest update not work with node version 10.15.3?

About 1-2 month ago, I was using 2.9.4 javascript-obfuscator, and the cli command works just fine. But now I cannot use it.. it throws 'estraverse' cannot find module error. I've tried installing estraverse separately and it didn't work either. 

When I tried to use node version 14.15.4, the CLI works fine. Due to other packages, I need to use node version 10.15.3, is there a way to work around this? Thanks!

## Current Behavior

Error: Cannot find module 'estraverse'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.4523 (/Users/verina/.nvm/versions/node/v10.15.3/lib/node_modules/javascript-obfuscator/dist/webpack:/javascript-obfuscator/external "estraverse":1:18)
    at r (/Users/verina/.nvm/versions/node/v10.15.3/lib/node_modules/javascript-obfuscator/dist/webpack:/javascript-obfuscator/webpack/bootstrap:18:32)
    at Object.3900 (/Users/verina/.nvm/versions/node/v10.15.3/lib/node_modules/javascript-obfuscator/dist/webpack:/javascript-obfuscator/src/analyzers/calls-graph-analyzer/CallsGraphAnalyzer.ts:38:33)
    at r (/Users/verina/.nvm/versions/node/v10.15.3/lib/node_modules/javascript-obfuscator/dist/webpack:/javascript-obfuscator/webpack/bootstrap:18:32)
    at Object.5821 (/Users/verina/.nvm/versions/node/v10.15.3/lib/node_modules/javascript-obfuscator/dist/webpack:/javascript-obfuscator/src/container/modules/analyzers/AnalyzersModule.ts:8:30)
    at r (/Users/verina/.nvm/versions/node/v10.15.3/lib/node_modules/javascript-obfuscator/dist/webpack:/javascript-obfuscator/webpack/bootstrap:18:32)

**Comment by sanex3339** [comment]
Hi. Try to completely remove your package-lock.json file. Now the project uses the fork of `estraverse`

**Comment by verina09** [comment]
hi @sanex3339 thank you for your prompt reply! turned out my error is caused by the global install of javascript-obfuscator
